name: Promote DTAP artifact

on:
  push:
    branches:
      - main
  workflow_dispatch:

## add input to select environment (options dev/prod for poc)

permissions:
  contents: read # Read repository contents

concurrency:
  group: dtap-${{ github.ref }}
  cancel-in-progress: false

jobs:
  build:
    name: Build immutable artifact
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Generate timestamp
        id: ts
        run: echo "formattedDate=$(date +'%y%m%d.%H%M')" >> "$GITHUB_OUTPUT"

      - name: Package site
        env:
          ARTIFACT_NAME: site-${{ steps.ts.outputs.formattedDate }}.tgz
        run: tar -czf ${ARTIFACT_NAME} -C ./src *

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site-${{ steps.ts.outputs.formattedDate }}
          path: site-${{ steps.ts.outputs.formattedDate }}.tgz
          retention-days: 14
    outputs:
      formattedDate: ${{ steps.ts.outputs.formattedDate }}

  deployment:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    environment: Development # (replace with input.environment || "Development")
    permissions:
      pages: write # Deploy to github pages
      id-token: write # Deploy to github pages
    env:
      ARTIFACT_NAME: site-${{ needs.build.outputs.formattedDate }}
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
      - name: Validate Development artifact
        run: tar -tzf ${{ env.ARTIFACT_NAME }}.tgz | grep -E '^(index.html|styles.css|script.js)$'
      - name: Prepare Pages artifact
        run: mkdir site && tar -xzf ${{ env.ARTIFACT_NAME }}.tgz -C site
      - name: Configure GitHub Pages
        uses: actions/configure-pages@v5
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1


  #test:
  #  name: Deploy Test
  #  needs: development
  #  if: github.ref == 'refs/heads/main'
  #  runs-on: ubuntu-latest
  #  environment: Test
  #  steps:
  #    - name: Download artifact
  #      uses: actions/download-artifact@v4
  #      with:
  #        name: site-${{ github.sha }}
  #    - name: Validate Test artifact
  #      run: tar -tzf site-${{ steps.ts.outputs.formattedDate }}.tgz | grep -E '^(index.html|styles.css|script.js)$'
#
  #acceptance:
  #  name: Deploy Acceptance
  #  needs: build
  #  if: github.ref == 'refs/heads/main'
  #  runs-on: ubuntu-latest
  #  environment: Acceptance
  #  steps:
  #    - name: Download artifact
  #      uses: actions/download-artifact@v4
  #      with:
  #        name: site-${{ github.sha }}
  #    - name: Validate Acceptance artifact
  #      run: tar -tzf site-${{ steps.ts.outputs.formattedDate }}.tgz | grep -E '^(index.html|styles.css|script.js)$'
#
  #production:
  #  name: Deploy Production
  #  needs: build
  #  if: github.ref == 'refs/heads/main'
  #  runs-on: ubuntu-latest
  #  environment: Production
  #  steps:
  #    - name: Download artifact
  #      uses: actions/download-artifact@v4
  #      with:
  #        name: site-${{ github.sha }}
  #    - name: Prepare Pages artifact
  #      run: mkdir site && tar -xzf site-${{ steps.ts.outputs.formattedDate }}.tgz -C site
  #    - name: Configure GitHub Pages
  #      uses: actions/configure-pages@v5
  #    - name: Upload Pages artifact
  #      uses: actions/upload-pages-artifact@v3
  #      with:
  #        path: site
  #    - name: Deploy to GitHub Pages
  #      id: deployment
  #      uses: actions/deploy-pages@v4