name: "Terraform Apply"
run-name: >-
  Terraform apply | ${{ github.event_name == 'workflow_dispatch'
    && 'manual'
    || github.ref_name }}

on:
  workflow_dispatch:
    inputs:
      instanceDirectory:
        description: 'Terraform instance directory'
        required: true
        default: './iac'

  push:
    branches:
      - main
      
permissions:
  contents: read

concurrency:
  group: tfapply-${{ github.ref }}
  cancel-in-progress: false

jobs:
  dev:
    uses: $/.github/workflows/terraform-apply-template.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: dev
      github_environment: Development
      instance_directory: ${{ inputs.instanceDirectory || './iac' }}
    secrets: inherit

  prod:
    needs: dev
    uses: $/.github/workflows/terraform-apply-template.yml
    permissions:
      contents: read
      id-token: write
    with:
      environment: prod
      github_environment: Production
      instance_directory: ${{ inputs.instanceDirectory || './iac' }}
    secrets: inherit
