name: "Terraform Plan"
run-name: >-
  Terraform plan | ${{ inputs.environment || 'dev' }} | ${{ github.event_name == 'pull_request'
    && format('PR #{0}', github.event.pull_request.number)
    || github.event_name }}

on:
  workflow_dispatch:
    inputs:
      instanceDirectory:
        description: 'Terraform instance directory for single-page application'
        required: true
        default: './iac'
      environment:
        description: 'Environment (dev/prod)'
        required: true
        default: 'dev'

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

env:
  TF_IN_AUTOMATION: true
  TF_INPUT: false
  TF_WARN_OUTPUT_ERRORS: true
  TF_WORKING_DIR: ${{ inputs.instanceDirectory || './iac'}}
  TF_ENVIRONMENT: ${{ inputs.environment || 'dev' }}

permissions:
  contents: read #read repository content

concurrency:
  group: tfplan-${{ inputs.environment || 'dev' }}
  cancel-in-progress: false

jobs:
  plan:
    name: "Plan"
    permissions:
      id-token: write # write id-tokens
    #environment: Development
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Terraform plan
        uses: ./.github/actions/terraform-plan
        with:
          working-directory: ${{ env.TF_WORKING_DIR }}
          environment: ${{ env.TF_ENVIRONMENT }}
          azure-client-id: ${{ secrets.AZURE_CLIENT_ID }}
          azure-tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          azure-subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
