name: "Terraform Plan"
run-name: >-
  Terraform plan | ${{ inputs.environment || 'dev' }} | ${{ github.event_name == 'pull_request'
    && format('PR #{0}', github.event.pull_request.number)
    || github.event_name }}

on:
  workflow_dispatch:
    inputs:
      instanceDirectory:
        description: 'Terraform instance directory for single-page application'
        required: true
        default: './iac'

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: read

concurrency:
  group: tfplan-${{ github.ref }}
  cancel-in-progress: false

jobs:
  dev-plan:
    permissions:
      contents: read #read repository content
      id-token: write #write id tokens
    uses: $/.github/workflows/terraform-plan-template.yml
    with:
      environment: dev
      instance_directory: ${{ inputs.instanceDirectory || './iac' }}
    secrets: inherit

  prod-plan:
    permissions:
      contents: read #read repository content
      id-token: write #write id tokens
    uses: $/.github/workflows/terraform-plan-template.yml
    with:
      environment: prod
      instance_directory: ${{ inputs.instanceDirectory || './iac' }}
    secrets: inherit
